### ISSUE TITLE
Install not in Default Directory

### ISSUE THREAD

**Issue by Jayshua83** [MartinSGill/SubnauticaWatcher#10]
Is there any way to have a config file where we can hardcode our Subnautica install path into? Mine is not Default and it asks every time I update or reinstall Subnautica Watcher.

**Comment by MartinSGill** [comment]
There is a fix in the code for that already. I've just not triggered a build for it yet. I'll see if I can get a build out.

**Comment by MartinSGill** [comment]
Should be fixed in v0.10 https://github.com/MartinSGill/SubnauticaWatcher/releases/tag/0.10.3
