### ISSUE TITLE
Player location not updating

### ISSUE THREAD

**Issue by skasowitz** [MartinSGill/SubnauticaWatcher#23]
Fresh installation of mod. Map loads, but player location appears to be fixed to its initial state in the save file. Loading a few different saves moves the cursor, but fails to update. Vehicle locations are also static and appear wherever they are in the loaded save file.

**Comment by OrihalconZA** [comment]
Make sure player updates is switched on in the settings tab. Just about the only thing I can think off on short notice.

**Comment by MartinSGill** [comment]
It sounds as though the web app lost contact with the game. This can happen if the game is unresponsive for a while and the webapp gives us trying to contact it.

Al @OrihalconZA has said, open the menu and ensure "game updates" is enabled.
