### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by hhrhhr** [MartinSGill/SubnauticaWatcher#4]
1. What is the principle of work (injection into game files / parsing saves / ...)?
2. How much can this affect performance?
3. Can I open a browser on another computer on the network, not just localhost?

**Comment by MartinSGill** [comment]
1. If I understand your question correctly then this mod works by adding a primitive webserver to the game that provides data and the web page.
2. Hardly at all. Each request is in it's own thread, and happen multi-second intervals and most of the map processing happens in the webbrowser and not the game. Any impact will mostly come from running a web browser in addition to your game.
3. In theory, yes. You need to use your computer's actual IP address or hostname, and you need to ensure your firewall allows incoming connections on port 63030.

**Comment by hhrhhr** [comment]
1. I meant where the data comes from, the coordinates of the player, for example. Do you use the Harmony library to intercept internal gaming functions? I'm poorly versed in C# and Unity, that's why I'm asking.

**Comment by MartinSGill** [comment]
Yes, the installer patches the main game logic dll to gain access to that data. I use harmony.
